### ISSUE TITLE
This is an excellent application

### ISSUE THREAD

**Issue by ZaynJarvis** [jarrettyeo/blackbox#3]
I am thinking, we could deploy this feature to a server and setup a frontend web page for it.

Could you introduce me to the structure of the source code for this app?

Thank you!

**Comment by ZaynJarvis** [comment]
I suppose its using selenium and chrome drive is it?

**Comment by ZaynJarvis** [comment]
And I notice that upon certain level, BlackBox cannot extract files from those folder.
We shall find a way to correct this bug.

**Comment by jarrettyeo** [comment]
@ZaynJarvis My apologies for the late reply. I've open sourced the code.

**Comment by ZaynJarvis** [comment]
Thank you, Jerrett.
